### ISSUE TITLE
ModuleNotFoundError: No module named 'msilib'

### ISSUE THREAD

**Issue by kode-git** [kode-git/NeMo-virtual-assistant#11]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/kode/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/kode/miniconda3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/core/management/base.py", line 438, in check
    all_issues = checks.run_checks(
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 448, in check
    for pattern in self.url_patterns:
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 634, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kode/Desktop/NeMo-virtual-assistant/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 627, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/kode/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/kode/Desktop/NeMo-virtual-assistant/translator/urls.py", line 18, in <module>
    from nemo_app import views
  File "/home/kode/Desktop/NeMo-virtual-assistant/nemo_app/views.py", line 5, in <module>
    from nlp.QAModel import QAModel
  File "/home/kode/Desktop/NeMo-virtual-assistant/nlp/QAModel.py", line 1, in <module>
    from msilib.schema import Error
ModuleNotFoundError: No module named 'msilib'

**Comment by kode-git** [comment]
@andreagurioli1995 find the package for it

**Comment by kode-git** [comment]
**Solution:** pip install nemo_toolkit[all] --no-cache
